### ISSUE TITLE
Callback number never added to callback Queue

### ISSUE THREAD

**Issue by LucMacPaquet** [aws-samples/amazon-pinpoint-connect-callback-requestor#6]
HI

When doing a test in Lambda I got this
2020-04-16T16:01:29.474Z	f66639d2-6005-47e4-a152-2c6c6011d44c	INFO	InvalidParameterException: DestinationPhoneNumber not in E164 format

It's INFO, so not. problem

Got this at the end 
2020-04-16T16:01:29.703Z	f66639d2-6005-47e4-a152-2c6c6011d44c	INFO	Successfully confirmed the call back via SMS to +(my phone number)
Al got the text message saying that my number had been added to the queue.

But, that number is never added to the callback Queue.

Where could I look to troubleshoot this ?

Thanks

**Comment by ILAsoft** [comment]
Hi @LucMacPaquet - that sounds like a full reject by Connect system. You never got the "Successfully issued call back to " in the logs, did you? Can you add the number to the Lambda output to confirm how it is coming over - top of the issueCallBack function add something like the following: console.log("Trying to issue call back via " + FakeNumber + " to " + originationNumber); -- see what it outputs. It should just be plane digits with no dashes, etc. and with the country code included (for both).

**Comment by LucMacPaquet** [comment]
Hi @ILAsoft 

Yes I got this : 

{
    "originationNumber": "+1418.......",
    "destinationNumber": "+1587.......",
    "messageKeyword": "Assist",
    "messageBody": "Teams",
    "inboundMessageId": "5a39f61a-1765-57a9-9d1c-a1089f019773",
    "previousPublishedMessageId": "s7nnbj2sdc3mdm4ngq3i6mmk0c55j8qmhf758d00"
}

2020-04-16T16:21:57.893Z	cc2205fa-d508-4507-ad24-78b0c4ad8411	INFO	Successfully confirmed the call back via SMS to +1418.....   END RequestId: cc2205fa-d508-4507-ad24-78b0c4ad8411

**Comment by LucMacPaquet** [comment]
And I don't have a Connect instance Log. Where should I look?
Thanks

**Comment by ILAsoft** [comment]
Can you confirm the "FakeNumber" number is set properly though? The output you pasted above is what is coming into your Lambda, but when you call Connect to place the callback request in, you have to call on the issued Connect's phone # aka that FakeNumber parameter (an attribute you have to set - as per step 4 in the Readme).

If it is all good, the lambda in issueCallBack (https://github.com/aws-samples/amazon-pinpoint-connect-callback-requestor/blob/c818a6a03f5a2bdcd507a8b8f961fbd5a7112bfe/src/app.js#L114) specifically has a check for failure to issue call back. You should either see "An error occurred." or the "Successfully issued call back" (the confirmed via SMS is another story). If you are not getting the latter, is it safe to assume you are getting the "error" note and the "DestinationPhoneNumber not in E164 format" is following it? I would output that paramsCall object that it uses (it would also include that "FakeNumber" value/parameter, among other things), so right before the actual call into Connect at https://github.com/aws-samples/amazon-pinpoint-connect-callback-requestor/blob/c818a6a03f5a2bdcd507a8b8f961fbd5a7112bfe/src/app.js#L125 -- right before it, output paramsCall (just like you are showing here the Sns.Message).

**Comment by LucMacPaquet** [comment]
Hi, the first problem is solved. The wrong format error was caused by my fakenumber. "+1" was missing. 

But, nothing is added to my callback queue. Any idea where to look at?
![image](https://user-images.githubusercontent.com/18090818/79580110-856a3000-8096-11ea-87ae-40fe4e0e59cc.png)
Also, my trigger keyword is "Teams", why i see "Assist" and "Teams" in this log:
{
    "originationNumber": "+1418......",
    "destinationNumber": "+1587.......",
    "messageKeyword": "Assist",
    "messageBody": "Teams",
    "inboundMessageId": "1b110c42-6d8c-587d-bec4-5b51d3e509bc",
    "previousPublishedMessageId": "k8eovl16hn2kvuj5dmgsmufn7nq8q7rt4phvitg0"
}

Could it be a reason why nothing is added to the Queue?

Thanks a lot for your help.

**Comment by LucMacPaquet** [comment]
FYI, on the phone, after sending "Teams" to my SMS number to be added to the queue, I'll receive the 2 acknowledges, the first is the response linked to "Teams" in Pinpoint and the second is the message from Lambda "Your number has been added to the queue".

**Comment by LucMacPaquet** [comment]
Yeah... everything is working fine now.

Not sure what I did but all the workflow is working now. 

Thans=ks

**Comment by Shiva-ibex** [comment]
HI

call is getting but its unable to deliver message, below is the error from lambda console

START RequestId: e2b20b15-6ad9-4b05-bc84-325179b7a75c Version: $LATEST
2020-12-01T05:16:44.694Z	e2b20b15-6ad9-4b05-bc84-325179b7a75c	INFO	Received event: {"originationNumber":"+14xxxxxx7","messageBody":"assist"}
2020-12-01T05:16:45.543Z	e2b20b15-6ad9-4b05-bc84-325179b7a75c	INFO	Failed to send SMS confirmation:
2020-12-01T05:16:45.563Z	e2b20b15-6ad9-4b05-bc84-325179b7a75c	INFO	{
  '+14xxxxx7': {
    DeliveryStatus: 'PERMANENT_FAILURE',
    StatusCode: 404,
    StatusMessage: 'Resource not found'
  }
}

**Comment by ILAsoft** [comment]
Hi @Shiva-ibex -- it looks like you are getting a rejection when sending back a response (reply) via Pinpoint. Usually it is because of Pinpoint SMS channel not being setup - please verify that the right application/project id is configured on Lambda. Please also verify that you are able to send messages via Pinpoint itself to this number (eg via Pinpoint's Console Test Message functionality) - if it works, try sending similar values as in the Lambda but via the CLI to see where the issue may be.

Also, since this does not appear to be related to the original issue ("Callback number never added to callback Queue"), please remember to open a new issue if you do need further assistance with this solution.
